/**
 * MIT License
 * Copyright 2020 - IBM Corp.
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions: The above copyright
 * notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

const Service = require('../service');


/**
 * A class for making token related requests to OIDC.
 * @extends Service
 * @author Adam Dorogi-Kaposi <adam.dorogi-kaposi@ibm.com>
 */
class TokenService extends Service {
  /**
   * Create a new {@link TokenService} object.
   * @param {Object} auth The credentials to authenticate to OIDC.
   * @param {string} baseURL The base URL for the OIDC API.
   * @param {Object} context The context to send for assessment.
   * @param {string} context.sessionId The session ID generated by the
   * user-agent, using an Adaptive client SDK.
   * @param {string} context.userAgent The user-agent, typically obtained form
   * the User-Agent HTTP header.
   * @param {string} context.ipAddress The IP address of the user-agent.
   */
  constructor(auth, baseURL, context) {
    super(auth, baseURL, context, 'x-www-form-urlencoded');
  }

  /**
   * Revoke an access token.
   * @param {string} accessToken The access token to revoke.
   */
  async revokeAccessToken(accessToken) {
    await this.post('/v1.0/endpoint/default/revoke',
        {token: accessToken});
  }

  /**
   * Refresh an access token.
   * @param {string} refreshToken The refresh token to refresh with.
   * @return {Promise<Object>} The HTTP response body for the refresh token
   * request, containing the new access and refresh tokens.
   */
  async refreshAccessToken(refreshToken) {
    const response = await this.post('/v1.0/endpoint/default/token',
        {grant_type: 'refresh_token', scope: 'openid',
          refresh_token: refreshToken,
          context: this._context});
    return response.data;
  }

  /**
   * Introspect an access or refresh token.
   * @param {string} token The access or refresh token to introspect.
   * @param {string} [tokenTypeHint] The token type. This attribute is an
   * optional hint about the token that is being introspected. Possible values
   * are <code>access_token</code> and <code>refresh_token</code>.
   * @return {Promise<Object>} The HTTP response body for the token introspect
   * request, which is an object containing an <code>"active"</code> property
   * indicating whether the introspected token is valid or invalid. Other
   * properties are also included in the introspection result when the
   * <code>"active"</code> status is <code>true</code>.
   */
  async introspectToken(token, tokenTypeHint) {
    const response = await this.post('/v1.0/endpoint/default/introspect',
        {token, token_type_hint: tokenTypeHint});
    return response.data;
  }

}

module.exports = TokenService;
